### PR TITLE
ElasticSuite/issues#5172 add DHL last regex

### PR DESCRIPTION
**Pull request by danielfebrero**
https://github.com/ElasticSuite/scramble4/issues/10394 add DHL last regex

Captura de pantalla 2021-01-25 a las 11 36 18

### CODE REVIEW

**Comment by danielfebrero** [comment]
@lyleunderwood I added a regex for DHL

**Review by lyleunderwood — APPROVED** [review]

**Comment by danielfebrero** [comment]
@lyleunderwood omg I have no write access, I cannot merge this

**Comment by lyleunderwood** [comment]
ack

**Comment by lyleunderwood** [comment]
you should now have access

**Pull request merged**
